Repository wecode-bootcamp-korea/26-1st-Wedibooks-backend, pull requests merged in 2021-11, with the labels that each got.

#1 [Wedibooks] 모델링 구현
  Wedibooks/settings.py
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/views.py
  products/__init__.py
  products/admin.py
  products/apps.py
  products/migrations/0001_initial.py
  products/migrations/0002_auto_20211103_0521.py
  products/migrations/__init__.py
  products/models.py
  products/tests.py
  products/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: Status: 리뷰 요청

#3 [Wedibooks] 회원가입 기능 구현
  Wedibooks/urls.py
  requirements.txt
  users/urls.py
  users/views.py
Labels: Status: 수정 요청

#4 [Wedibooks] 컬럼명 및 model field 수정
  users/migrations/0002_auto_20211105_0608.py
  users/models.py
  users/views.py
Labels: Status: 리뷰 요청

#5 [Wedibooks] SigninView 기능 구현
  Wedibooks/settings.py
  requirements.txt
  users/urls.py
  users/views.py
Labels: Status: Accepted

#6 [Wedibooks] 상세페이지 데이터 View 기능 구현
  Wedibooks/urls.py
  products/models.py
  products/urls.py
  products/views.py
Labels: Status: Accepted

#8 [Wedibooks] 로그인 decorator 기능 구현
  users/utils.py
Labels: Status: 리뷰 요청

#9 [Wedibooks] model 수정
  orders/__init__.py
  orders/admin.py
  orders/apps.py
  orders/migrations/__init__.py
  orders/models.py
  orders/tests.py
  orders/views.py
  products/migrations/0004_alter_product_index.py
  products/models.py
  reviews/__init__.py
  reviews/admin.py
  reviews/apps.py
  reviews/migrations/__init__.py
  reviews/models.py
  reviews/tests.py
  reviews/views.py
Labels: Status: Accepted

#10 Modify: models 수정
  products/migrations/0005_auto_20211110_0525.py
  products/models.py
Labels: Status: Accepted

#11 [Wedibooks] migrations
  Wedibooks/settings.py
  orders/migrations/0001_initial.py
  orders/models.py
  reviews/migrations/0001_initial.py
  reviews/models.py
Labels: Status: Accepted

#12 [Wedibooks] ProductView 수정
  products/views.py
Labels: Status: Accepted

#7 Add : Productlistview in views.py of products
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#13 [Wedibooks] ReviewView 기능 구현
  Wedibooks/urls.py
  reviews/urls.py
  reviews/views.py
Labels: Status: 리뷰 요청

#14 Modified : ProductListView(주석 삭제)
  products/views.py
Labels: Status: Accepted

#15 Modified : ProductListView의 출력 result item 추가 및 추천 도서 경우 if문으로 항목 추가
  products/views.py
Labels: Status: 리뷰 요청
